#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    # Write your code here
    
    l = len(arr)
    left_sum = 0
    right_sum = 0
    left_index = 0
    right_index = l-1
    for i in range(0,l):
        left_sum+=arr[i][left_index]
        right_sum+= arr[i][right_index]
        left_index+=1
        right_index-=1
    
    return abs(left_sum-right_sum)
    
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
